### ISSUE TITLE
sqlite3 console 

### ISSUE THREAD

**Issue by ixnp** [learn-co-curriculum/python-p3-manual-migrations-and-downgrades#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204245?module_item_id=468031

### Concern

Building a Migration Manually: This is the first time the sqlite3 command from the command line is mentioned. It might be confusing to add it here. 

### Suggested Changes

Add a section about the sqlite3 console to the SQL module.

**Comment by professor-ben** [comment]
this does actually come up (briefly) in "Setting up SQLite"

it is definitely not used very much, in favor of the SQLite Viewer in VSCode.

i think that it's valuable here as a reminder of this as an option- as far as expansion of earlier material goes, i think we'll wait until we're ready to refactor SQL fundamentals and write write the optional advanced SQL module post-build 4.
