### ISSUE TITLE
Delete downgraded migration?

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p3-manual-migrations-and-downgrades#2]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204245?module_item_id=468031

### Concern

If we wanted to downgrade a migration to a previous migration, and not have the migration we downgraded from be present in the next batch of migrating, are we just supposed to delete the file? Or is there a way to keep that migration around but specify that we don't want it included in the next migrations we run? What's best practice? This might be helpful context for students. Thanks!

**Comment by professor-ben** [comment]
Hi Matt,

I actually fixed this around the time you submitted and just haven't synced the course with the blueprint yet. I'm hoping to do that today, but you should see your suggestion reflected in the repo on GitHub now.

Thanks,
Ben
